### ISSUE TITLE
Scatter size should handle null values

### ISSUE THREAD

**Issue by fdion** [adamerose/PandasGUI#114]
Using a column with null values (ie. demo data `penguins.body_mass`) on size in a scatter plot produces this error:

```
ValueError: 
    Invalid element(s) received for the 'size' property of scatter.marker
        Invalid elements include: [nan]

    The 'size' property is a number and may be specified as:
      - An int or float in the interval [0, inf]
      - A tuple, list, or one-dimensional numpy array of the above
```

To provide a more seamless experience, it should instead zero out the null values before calling `px.scatter` if a size column is present (or maybe add a filter ` `column name` > 0` ?)

As a further thought, should any exception on hitting `finish` produce a popup?

**Comment by adamerose** [comment]
I'm hesitant to continue adding logic inside the Grapher towards improving default plot behaviors like this. This kind of thing should ideally be handled by Plotly Express, which is meant to be an easy-to-use wrapper around Plotly, but unfortunately it often falls short and requires manual tweaking.

We've already been implementing some features on top of Plotly Express:
- aggregation and sorting in line/bar plots #106 
- removing nulls from `size` #114
- intelligent title generation #101 

...and if you think about it those are really just improvements to Plotly Express to give more seamless EDA and not really tied specifically to PandasGUI.

I think the best route forward might be to pull all this logic out of PandasGUI and make a new standalone graphing library that aims to be as seamless as possible and handles all the automatic magic you'd want during EDA. This would also greatly simplify the integration of Code History with the Grapher in PandasGUI since I can just make the code history a line that calls one function from that graphing package.

But before creating a new package wrapping Plotly or Plotly Express I would want some more discussion and also revisit whether there is an existing solution. HoloViews comes to mind, but I'm not sure how much more seamless it makes things compared to Plotly Express, I need to try it out when I have time. 

What are your thoughts?

> As a further thought, should any exception on hitting finish produce a popup?

The feature I had in mind for a while is a new tab in the GUI called `Console` that shows all warnings and error messages, and blinks yellow when a new message appears. This would cover this but not be specific to only the Grapher

**Comment by fdion** [comment]
It does make sense. I was thinking about that. Was also thinking about how pandas allow for different plotting systems. The idea is good, but the implementation is flawed, in that you have to specify the right kwargs to each engine, kind of defeats the purpose. So I was thinking about a more universal API for pre-defined data visualizations. But then the scope hit me...

**Comment by fdion** [comment]
Also, I think a console tab would be great

**Comment by adamerose** [comment]
> It does make sense. I was thinking about that. Was also thinking about how pandas allow for different plotting systems. The idea is good, but the implementation is flawed, in that you have to specify the right kwargs to each engine, kind of defeats the purpose. So I was thinking about a more universal API for pre-defined data visualizations. But then the scope hit me...
> 
> Regarding libraries, plotly express for all its fault is currently the least incomplete and has a pretty solid templating engine, can fall back to plotly (add_traces, layout etc) and is consistent across interactive, html export, and print. It does have some serious limitations of course, like no dual Y axis (two different scales). But having used plotly, bokeh, altair and pygal (and mpld3 etc), they all have in one way or another serious limitations. Altair, if it had 3d hardware acceleration, would be a great dataviz library.

Yeah I spent some more time this weekend comparing options and I'm also leaning towards sticking with Plotly. Made some notes here if you want to add anything https://github.com/adamerose/PandasGUI/issues/118
