### ISSUE TITLE
v2.10.1 doesn't show graph type of the type highlighted

### ISSUE THREAD

**Issue by miglto** [adamerose/PandasGUI#119]
PLEASE FILL OUT THE TEMPLATE

**Describe the bug**  
v2.10.1 doesn't show graph type of the type highlighted

**Environment**
Ubuntu 20.04, python 3.8.2, macbook pro (running Ubuntu natively, only OS installed in computer)

**Package versions**  
v0.2.10.1

EXAMPLE OUTPUT
![Screenshot from 2021-03-16 17-14-57](https://user-images.githubusercontent.com/51788468/111381037-8a0ae000-867b-11eb-9e7b-78e6a7237870.png)

**Comment by miglto** [comment]
Tried to upgrade pyQt5, and now I am getting this error:

![Screenshot from 2021-03-16 17-38-17](https://user-images.githubusercontent.com/51788468/111383394-8462c980-867e-11eb-8505-6bb69845d220.png)

**Comment by miglto** [comment]
Fixed error in my second post here but the display issue persists.

**Comment by miglto** [comment]
Adding/correcting some info:
Python version is 3.8.5
pyqt5 version is 5.15.4

**Comment by miglto** [comment]
Any comments on this? Thx.

**Comment by adamerose** [comment]
I didn't comment because I was redesigning the Grapher so UI bug fixes on the old one weren't worth doing. Can you try the latest version with `pip install git+https://github.com/adamerose/pandasgui.git`? I think your problem should be fixed since the graph selection widget was replaced, reopen this if it's still happening.
