### ISSUE TITLE
Ability to set Filters in show() command

### ISSUE THREAD

**Issue by soberhofer** [adamerose/PandasGUI#139]
It would be great, if it was possible to preconfigure a list of filters in the python code.

I'm not sure if it is possible through custom kwargs or similar, but i tried different things and was not able to do it.

Is this something that should currently be possible? If so where can I find documentations on this?

Thanks a lot

**Comment by adamerose** [comment]
You can't do it directly as a `show` argument but you can do it programmatically on the GUI instance like this:

```python
from pandasgui import show
from pandasgui.datasets import pokemon

gui = show(pokemon)
for expr in ['HP > 90', 'Attack > 100']:
    gui.store.selected_pgdf.add_filter(expr)
```

Any action in the GUI can be done programmatically and all actions that affect a DataFrame are defined in `pandasgui.store.PandasGuiDataFrameStore`. You can access them by name or use `.selected_pgdf` to access the currently selected one. In this case you could use either `gui.store.selected_pgdf` or `gui.store.data['pokemon']`

![image](https://user-images.githubusercontent.com/10884874/120233704-6855d980-c224-11eb-95d2-488363366953.png)



> If so where can I find documentations on this?
I basically have no documentation other than what's in the README, I was putting it off since I was making lots of breaking changes with releases but planning to make better docs in the next few months
