### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "" even though it was found. 

### ISSUE THREAD

**Issue by blaubaer01** [adamerose/PandasGUI#140]
Hi, 

I got this message, and the Gui doesn't start.

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

I use this script in windows and at my Mint Computer too without any issue.
I have tried to found any help by Google, but I got no useful help.

**Environment**
OS: Bunsenlabs OS (Linux)
Python: 3.7.3
IDE: Terminal / Spyder3

**Package versions**  
ipython==7.23.1
ipython-genutils==0.2.0
jupyter-client==5.2.3
jupyter-core==4.4.0
pandasgui==0.2.10.1
plotly==4.14.3
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
PyQtWebEngine==5.15.4
PyQtWebEngine-Qt5==5.15.2

**Comment by adamerose** [comment]
I see a few posts on this in the [Qt bug tracker](https://bugreports.qt.io/browse/QTCREATORBUG-24962?jql=text%20~%20%22qt.qpa.plugin%22) and [forum](https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found).

I'm closing since this isn't specific to pandasgui and I can't really help debug general PyQt issues, my only advice is to look through the Qt forums and bug tracker or try installing through conda instead of pip.

**Comment by blaubaer01** [comment]
It's okay for me.I will try conda. Thanks.
