### ISSUE TITLE
Mouse module does not support Mac

### ISSUE THREAD

**Issue by fdion** [adamerose/PandasGUI#145]
PLEASE FILL OUT THE TEMPLATE

**Describe the bug**  
The newly introduced `mouse` module requirement only works on Linux and Windows. Is there a substitute that could be used instead that would cover all 3 platforms?

**Environment**
OS: Any Mac OS
Python: any
IDE: N/A

**Package versions**  
N/A

**Comment by adamerose** [comment]
I replaced `pynput` with `mouse` because `mouse` had a simpler API, didn't realize it didn't support Linux. I also noticed both `pynput`  and `mouse` were causing very bad mouse cursor lag for me but I think it's just a Windows problem so I check the OS and use `win32api` on Windows. I'll revert `mouse` to `pynput`
