### ISSUE TITLE
Translate to spanish

### ISSUE THREAD

**Issue by sofiamartin** [adamerose/PandasGUI#148]
I'd like to translate the app to **spanish**. 

I looked the code and the words in english are all over the code.

Are you using some tools for automate the translations?

thank you

**Comment by adamerose** [comment]
Right now there is no translation being done. I think it's out of scope since the entire project is in English it would be a huge effort to maintain everything in multiple languages. Someone translated the docs and some components to Chinese a while back but inevitably once I modified code and added/changed features it became out of date and I had to remove it.
