### ISSUE TITLE
Error when import pandasgui

### ISSUE THREAD

**Issue by hossam-houssien** [adamerose/PandasGUI#174]
PLEASE FILL OUT THE TEMPLATE

**Describe the bug**  
getting error when try to import pandasgui
```
λ python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pandasgui import show
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\hossam\bin\Continuum\anaconda3\lib\site-packages\pandasgui\__init__.py", line 15, in <module>
    from pandasgui.gui import show
  File "D:\hossam\bin\Continuum\anaconda3\lib\site-packages\pandasgui\gui.py", line 13, in <module>
    from pandasgui.store import PandasGuiStore
  File "D:\hossam\bin\Continuum\anaconda3\lib\site-packages\pandasgui\store.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Environment**
>OS: Microsoft Windows [Version 10.0.18362.329]
Python: Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
IDE: none

**Package versions**  
```
ipython==6.1.0
ipython_genutils==0.2.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
jupyterlab==0.31.8
jupyterlab-launcher==0.10.2
jupyterlab-widgets==1.0.0
notebook==5.0.0
pandasgui==0.2.13
plotly==5.3.1
PyQt5==5.13.2
PyQt5_sip==4.19.19
PyQtWebEngine==5.13.2
```

**Comment by adamerose** [comment]
It seems like `from __future__ import annotations` doesn't work for Python versions 3.6 or earlier. I don't want to lose the annotations feature because it improves intellisense and developer UX and Python 3.6 is reaching end of life in under 2 months anyway. So sorry but I'm marking this as a won't-fix and will only support 3.7+ going forward - I'll update the setup.py to indicate this
