### ISSUE TITLE
Running it as an application

### ISSUE THREAD

**Issue by someoneonboard1** [adamerose/pandasgui#22]
Sorry for noob question but I am trying to run the application on VS Code but once I execute show(df) as specified on the demo.py file, the GUI screen opens and closes right away. I am not sure if this tool is intended to run that way. Am I missing something?

I am also getting the following message:
MatplotlibDeprecationWarning:
The matplotlib.backends.backend_qt4agg backend was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg

Edit: I figured out how to run it. But it would be helpful if it can be run as a desktop application

**Comment by adamerose** [comment]
Hi @someoneonboard1 !

This has to do with whether or not you pass in `settings={'block':True}` which blocks all code execution until the GUI is closed.

There are two main usecases for PandasGui
- In a Python script - this should block otherwise the script will continue or finish without giving the user a chance to interact
- In iPython - this should not block so you can run still commands while the GUI is open

I changed the default to non-blocking but forgot to update the demo to account for this, I'll fix that.

> MatplotlibDeprecationWarning

I actually just switched from Seaborn to Plotly so I'll get rid of this when I go clean up and remove all the MPL imports and usage. 

I'll close this when I finish these things. Thanks for the issue 👍

**Comment by someoneonboard1** [comment]
Thanks for replying. I have been searching for this type of tool for a while. A feature that I would like to be added is Load dataframe(csv file) from GUI and use it to plot/view data. I am willing to contribute as well with whatever knowledge that I have. I also noticed that grapher is not working yet. I am planning to go through the code over the weekend and see if I can understand whats going on.

**Comment by adamerose** [comment]
> Load dataframe(csv file)

You can already drag a CSV file into the PandasGui nav area and it'll import it. I should add this to the Edit menu and docs

> I also noticed that grapher is not working yet

Oh I've been using the Grapher on my own computer for the past few days since adding it, if it's not working for you please make an issue

> I am planning to go through the code over the weekend and see if I can understand whats going on.

Good timing, I'm pushing some refactoring/code cleaning changes tonight

**Comment by adamerose** [comment]
- Removed matplotlib
- Fixed permission errors for Grapher
- Updated demo so it doesn't immediately close
