### ISSUE TITLE
Error bars in scatter plot

### ISSUE THREAD

**Issue by miglto** [adamerose/pandasgui#26]
Would like to be able to do this:

fig = px.scatter(df, x="strike", y="vol_mid", color="call_put", error_y="vol_bidask")

Thx

**Comment by adamerose** [comment]
I think this option is not too commonly used and don't want to clutter the defaults. What I'll do instead is make it possible to add additional custom kwargs then you can use any valid Plotly Express arguments like this in the Grapher.

**Comment by miglto** [comment]
That's even better.

**Comment by adamerose** [comment]
Done. I use `ast.literal_eval` to try parsing non-string arguments like lists and numbers, and if it's unable to parse the value it treats it as a string.

![image](https://user-images.githubusercontent.com/10884874/91771207-96808d00-ebb0-11ea-82f9-737de333429c.png)

**Comment by miglto** [comment]
Looks great. How do I get the graph builder? I updated to the latest in your repo (0.2.2.3)

**Comment by adamerose** [comment]
Oh yeah I should have mentioned it's not part of a release yet only committed it to the dev branch. You can install the latest changes with `pip install git+https://github.com/adamerose/pandasgui.git`

But since you mentioned it I do have enough changes for a new release so I'll update the readme and do release 0.2.3 tonight if you want to wait for that

**Comment by miglto** [comment]
Awesome. Thx.
