### ISSUE TITLE
Font size in plotly plot

### ISSUE THREAD

**Issue by miglto** [adamerose/PandasGUI#32]
The plotly plots on my macbook on Ubuntu 20.04 and pandasgui 0.2.3.2 have very tiny font. Wondering if there's a way to change this.. See pic below.

![PandasGui small font in plot](https://user-images.githubusercontent.com/51788468/93714956-15277500-fb34-11ea-96c8-21228bded784.png)

**Comment by adamerose** [comment]
What's your screen resolution, is it 4k? I don't have a mismatch between Plotly and PyQt like this, maybe Plotly doesn't properly scale up with high resolution.

Tagging this issue for help wanted since I'm tight on time lately and it's probably something that can be fixed by just changing the Plotly figure settings in plotly_viewer.py

**Comment by udaan42** [comment]
Hey, I would like to help if no one is working on this. Please let me know.

**Comment by miglto** [comment]
Please do

**Comment by ziliangok** [comment]
if pandasgui using plotly, it can using 
    fig = px.line(df, x='x', y='y')
    fig.layout.font.size = 12
    fig
for more information, you can check https://plot.ly/python/reference/#layout -> font

**Comment by miglto** [comment]
Was there any progress on this?
Thx.
