### ISSUE TITLE
Code export

### ISSUE THREAD

**Issue by adammclaurin** [adamerose/PandasGUI#59]
Are there any plans to add a feature to generate and export Python code for any transformation or visualization done in the GUI? That would be very useful for newcomers to Python/pandas/Plotly to help learn, and to use PandasGUI to bootstrap the code for more complicated scripts.

**Comment by adamerose** [comment]
Yeah this is on the feature tracker list but good to have an issue for it since it's a high priority feature. Aiming to get this one done by end of November

**Comment by adamerose** [comment]
Ok I added code history on dev branch. Try it out and let me know if you have any issues or feedback then I'll put a release on PyPi

@adammclaurin @broberg @santiariza15 @Krogenar @supernooba @am-technix @ardasamet0 @chottokun (pinging the people who upvoted)

**Comment by am-technix** [comment]
Thank you very much for this feature !
Especially for pivot, it helps to know how to do them by code.
I think **the filter commands should also be pushed** in the log, I don't see them.
Thanks again, PandasGUI is awesome !

**Comment by adamerose** [comment]
> Thank you very much for this feature !
> Especially for pivot, it helps to know how to do them by code.
> I think **the filter commands should also be pushed** in the log, I don't see them.
> Thanks again, PandasGUI is awesome !

Currently filters should always appear at the end of the log, not in the same order you apply them. Or do you not see it at all?

![image](https://user-images.githubusercontent.com/10884874/106385325-be616000-639d-11eb-9d9b-10b13475d838.png)

I did it like this because in PandasGUI filters are transient (they can be enabled/disabled) and the way this works under the hood is an unfiltered df is always stored and that is what modifications like cell edits and column sorts are applied to, and the filters are reapplied to it after any change. Otherwise filters would not be toggleable because you can't undo a filter unless you have the original. 

So I had two options for the code history...

1. Duplicate this logic in the code history, so there would be two df objects at each step `df` and `df_filtered` and filter state would be stored in a list of objects with properties for the query string, enabled state, and failed state.
2. Apply filters at the end simply as query strings with a snapshot of the current enabled non-failed filters. The problem with this is that if you create derived DataFrames or plots using Reshaper or Grapher, they will always be applied to the unfiltered data so you'd need to reorder the code to apply the proper filters beforehand.

I went with #2 since it keeps the output much cleaner and it is easy to rearrange or copy paste the filters where you want them.
