### ISSUE TITLE
does this work on remote jupyter lab?

### ISSUE THREAD

**Issue by animismus** [adamerose/pandasgui#63]
I tried the quickstart code but jupyterlab just hangs.

I wonder if it is because the jupterlab server is running on another machine? 

If so, is there something I could do to make this work without installing jupyterlab (python for that matter) locally? I would really like to try this.

**Comment by adamerose** [comment]
> I wonder if it is because the jupterlab server is running on another machine?

Yes that is why. Also doesn't work with Google Colab

> is there something I could do to make this work without installing jupyterlab (python for that matter) locally?

I don't think so, PyQt5 renders on the same machine it is running so I think you need to run it locally. I would recommend taking a look at https://github.com/man-group/dtale, I think it can run on remote servers since it's build on flask not PyQt5
