### ISSUE TITLE
Line plot is not working when there is too much blank cells in the dataframe

### ISSUE THREAD

**Issue by reboucasaraujo** [adamerose/pandasgui#66]
1) Code snippet ran ok, showing a window with a "test' button

2) pip freeze output:
ipython-genutils==0.2.0
jupyter==1.0.0
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==2.1.5
notebook==6.0.3
pandasgui==0.2.7
plotly==4.12.0
PyQt5==5.12
PyQt5-sip==4.19.19

3) Describe the bug:

**I have a dataframe with 46k lines and 2 columns (var1 and var2). Var2 has values for almost all lines but var1 only has values for 34 lines (the rest is np.NaN):**
![figure0_statistics](https://user-images.githubusercontent.com/59915219/99148684-e62b0c80-2667-11eb-87d3-dbb624c6568b.png)

**When I plot a line with "var2", it shows everything ok (figure1.png).** 
![figure1_var2line](https://user-images.githubusercontent.com/59915219/99148686-e75c3980-2667-11eb-966c-6efb15d24d6a.png)

**When I try to plot a line with "var1", nothing is shown on the plot (figure2.png), is this a bug?**
.......Only var1:
![figure2_var1line_bug](https://user-images.githubusercontent.com/59915219/99148688-e7f4d000-2667-11eb-87c3-c0cd3032e326.png)
.......Var1 and Var2 at the same time (shows only var2):
![figure2_var1line_bug2](https://user-images.githubusercontent.com/59915219/99148689-e7f4d000-2667-11eb-8ae1-a967070708fc.png)

**If I filter `var2` != np.NaN, then I get the plot of the 34 points.** 
![figure3_var1_filtered](https://user-images.githubusercontent.com/59915219/99148690-e88d6680-2667-11eb-8664-ca2f926ee47d.png)

**I'd like to plot var1 and var2 on the same plot without filtering anything, how can I do that?**

**Extra question: is there a way to plot var2 as markers only and var1 as a line?**

**Comment by adamerose** [comment]
Hi @reboucasaraujo, most of my Grapher code is just a thin wrapper over Plotly Express, the only exception is for line and bar plots I aggregate the mean within each `x` value... however that doesn't apply here since your example doesn't actually have anything under `x`. 

Your plot results are just `px.line(**kwargs)`, where `kwargs` is a dict of whatever you dragged and dropped in the Grapher.

So I think `px.line(df, y='var1')` should also give you a blank plot, which would mean your problem is with Plotly not PandasGUI. If that snippet doesn't give a blank plot then please re-open this and I can investigate on my end, otherwise I recommend asking on stackoverflow or making an issue on the Plotly github

**Comment by adamerose** [comment]
@reboucasaraujo 

> Extra question: is there a way to plot var2 as markers only and var1 as a line?

Yeah, you can click the Custom Kwargs button and add any Plotly Express arguments, I think thw `line_dash` argument might be what you need https://plotly.com/python-api-reference/generated/plotly.express.line.html#plotly.express.line

**Comment by reboucasaraujo** [comment]
Ok, @adamerose. Thank you for the feedback.
