### ISSUE TITLE
Unnamed columns unsupported in plots

### ISSUE THREAD

**Issue by brbatv** [adamerose/PandasGUI#75]
PLEASE FILL OUT THE TEMPLATE

**Describe the bug**  
Unnamed columns are not recognized in scatter plots. Naming the columns fixes this.  See picture : 
![bug_unnamed](https://user-images.githubusercontent.com/22215204/103694741-c21ae600-4f9b-11eb-8962-77cd7fb1ec3c.png)

**Environment**
OS:  Linux Mint
Python: (eg. 3.8.5)
IDE: Vscode

**Package versions**  
all latest

**Comment by adamerose** [comment]
Your column isn't unnamed, but its name is `0` as an integer. 

```
a = pd.DataFrame([1,2,3,4,5,6,7,8,9,10])
print(type(a.columns[0]))
Out[18]: <class 'int'>
```

The problem is my code assumes column names will be strings so it breaks. Getting everything to work correctly with column names of any type would be a struggle and not add much value... I think the solution that makes the most sense is I'll just force convert all column names to strings when imported into PandasGUI similar to how I don't allow duplicate column names
